language: bash

sudo: required

services:
  - docker

addons:
  mariadb: '10.0'

before_script:
  - mysql -uroot -e "create user 'yona'@'localhost' IDENTIFIED BY 'yonadan';"
  - mysql -uroot -e "set global innodb_large_prefix = ON;"
  - mysql -uroot -e "create database yona DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_bin;"
  - mysql -uroot -e "GRANT ALL ON yona.* to 'yona'@'localhost';"

script:
  - docker-compose build
  - docker-compose up -d
  - docker-compose logs

after_script:
  - docker-compose down

notifications:
  email: false
